Server:
  RunMode: debug
  HttpPort: 8888
  ReadTimeout: 60
  WrtieTimeout: 60
Web:
  DefaultPageSize: 10
  MaxPageSize: 100
  LogSavePath: logs
  LogFileName: app
  LogFileExt: .log
Mysql:
  Host: 127.0.0.1
  User: root
  Password: 123456
  DBName: blog_data
  TablePrefix: blog_
  Charset: utf8mb4
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30